version: "3.8"

services:
  app:
    build: .
    volumes:
      - .:/app
      - /app/.tox
      - /app/.poetry
    environment:
      - TEST=true
      - BEETHOVEN_MONGODB_HOST=mongodb
      - BEETHOVEN_MONGODB_USERNAME=user
      - BEETHOVEN_MONGODB_PASSWORD=password123
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password123

